version: '2.4'

services: 
  turku_parser:
    build: 
      dockerfile: Dockerfile.custom
      context: .
    volumes:
      - .:/app
    container_name: turku_parser
    ports:
      - 15000:7689
    mem_limit: 5g
    entrypoint: /bin/bash /app/docker_entry_point.sh server test_training parse_plaintext

