version: '2.4'

services: 
  turku_parser:
    build: 
      dockerfile: Dockerfile.custom
      context: .
    volumes:
      - .:/app
      - F:/experiment/model_confidence/models/models_uncert_1:/app/models_uncert_1
      - F:/experiment/model_confidence/models/models_uncert_2:/app/models_uncert_2
      - F:/experiment/model_confidence/models/models_uncert_3:/app/models_uncert_3
    mem_limit: 5g

  confidence_proxy:
    build: 
      dockerfile: Dockerfile.proxy
      context: .
    