FROM python:3.6.11-stretch

COPY ./requirements-cpu.txt /app/requirements-cpu.txt

RUN pip3 install --upgrade pip
RUN pip3 install -r /app/requirements-cpu.txt -f https://download.pytorch.org/whl/torch_stable.html

WORKDIR /app

ENTRYPOINT ["/bin/bash /app/docker_entry_point.sh server fi_tdt parse_plaintext"]