version: '2.4'

services: 
  turku_parser:
    build: 
      dockerfile: Dockerfile.custom
      context: .
    volumes:
      - .:/app
      - F:/experiment/model_confidence/models/models_uncert_0:/app/models_uncert_0
      - F:/experiment/model_confidence/models/models_uncert_1:/app/models_uncert_1
      - F:/experiment/model_confidence/models/models_uncert_2:/app/models_uncert_2
      - F:/experiment/model_confidence/models/models_uncert_3:/app/models_uncert_3
    mem_limit: 5g
  
  original_parser:
    depends_on: 
      - turku_parser
    image: turkunlp/turku-neural-parser:latest-fi-en-sv-cpu
    entrypoint: /bin/bash /app/docker_entry_point.sh server fi_tdt parse_plaintext
    mem_limit: 4g

  confidence_proxy:
    build: 
      dockerfile: Dockerfile.proxy
      context: .
    depends_on: 
      - turku_parser
      - original_parser
    volumes:
      - ./confidence_proxy.py:/app/confidence_proxy.py
    ports:
      - 5000:5000
    mem_limit: 60M
    